/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./templates/**/*.{js,ts,jsx,tsx,html}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
      },
      fontSize: {
        "xs-em": ".75em",
        "sm-em": ".875em",
        "base-em": "1em",
        "lg-em": "1.125em",
        "xl-em": "1.25em",
        "2xl-em": "1.5em",
        "3xl-em": "1.875em",
        "4xl-em": "2.25em",
        "5xl-em": "3em",
        "6xl-em": "4em",
      },
      spacing: {
        "0-em": "0em",
        "1-em": ".25em",
        "2-em": ".5em",
        "3-em": ".75em",
        "4-em": "1em",
        "5-em": "1.25em",
        "6-em": "1.5em",
        "7-em": "1.75em",
        "8-em": "2em",
        "9-em": "2.25em",
        "10-em": "2.5em",
        "11-em": "2.75em",
        "12-em": "3em",
        "16-em": "4em",
        "20-em": "5em",
        "24-em": "6em",
        "28-em": "7em",
        "32-em": "8em",
        "36-em": "9em",
        "40-em": "10em",
        "44-em": "11em",
        "48-em": "12em",
        "52-em": "13em",
        "56-em": "14em",
        "60-em": "15em",
        "64-em": "16em",
        "72-em": "18em",
        "80-em": "20em",
        "96-em": "24em",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/typography")],
};
