import { type NextPage } from "next";
import Head from "next/head";

import MainLayout from "src/components/layout/Main";

import HeroResume from "public/ilustrations/hero_resume.svg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>EasyResumeBuilder</title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="prose-xl flex flex-col-reverse items-center justify-center gap-4 px-10 py-4 md:flex-row mt-10">
          <div className="flex flex-col items-center md:items-start">
            <h1 className="text-center text-4xl leading-snug md:text-left">
              <span className="font-bold italic">Stand out</span> from the crowd
              with a tailored, professional CV
            </h1>
            <button className="rounded-lg bg-accent px-4 py-4">
              Get Started with your dream job today
            </button>
          </div>

          <div>
            <HeroResume className="h-96 w-96 xl:h-[600px] xl:w-[600px]" />
          </div>
        </div>
      </main>
    </>
  );
};

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
Home.getLayout = function getLayout(page: React.ReactNode) {
  return <MainLayout>{page}</MainLayout>;
};

export default Home;
